# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'Account', max_length=250)),
                ('webmail', models.CharField(blank=True, max_length=250, unique=True)),
                ('password', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineCC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'Account', max_length=250)),
                ('webmail', models.CharField(blank=True, max_length=250, unique=True)),
                ('password', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SubmitThesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'Account', max_length=250)),
                ('webmail', models.CharField(blank=True, max_length=250, unique=True)),
                ('password', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
