# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20161112_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='onlinecc_approval',
            field=models.BooleanField(default=True),
        ),
    ]
