# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20161112_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gymkhana_approval',
            field=models.BooleanField(default=False),
        ),
    ]
