# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20161112_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='thesis_manager_approval',
            new_name='submit_thesis',
        ),
    ]
