# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20161113_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant_registrar',
            name='name',
            field=models.CharField(default=b'Assi. Registrar', max_length=250),
        ),
        migrations.AlterField(
            model_name='onlinecc',
            name='name',
            field=models.CharField(default=b'OnlineCC Manager', max_length=250),
        ),
        migrations.AlterField(
            model_name='submitthesis',
            name='name',
            field=models.CharField(default=b'Thesis Manager', max_length=250),
        ),
    ]
