# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20161114_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='stud_faculty_status',
            name='faculty_remarks',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
